In [1]:
import numpy as np

In [2]:
l=[12,34,23,56]

In [4]:
type(l)

list

In [3]:
np.array(l)

array([12, 34, 23, 56])

In [6]:
type(np.array(l))

numpy.ndarray

In [8]:
np.array([23,34,23,54,23,54.])

array([23., 34., 23., 54., 23., 54.])

In [10]:
a=np.array([[12,23],[12,34]])

In [11]:
a

array([[12, 23],
       [12, 34]])

In [12]:
a[1]

array([12, 34])

In [14]:
a[0]

array([12, 23])

In [15]:
a[0][1]

23

In [21]:
a=np.array([12,23,45,23],ndmin=4)

In [22]:
a[0]

array([[[12, 23, 45, 23]]])

In [24]:
a[0][0][0][1]

23

In [25]:
b=np.array([[12,23],[12,34]])

In [26]:
b

array([[12, 23],
       [12, 34]])

In [27]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [28]:
np.mat([12,34,12,43])

matrix([[12, 34, 12, 43]])

In [29]:
s=[12,32,23,545,32]

In [30]:
np.asarray(s)

array([ 12,  32,  23, 545,  32])

In [31]:
np.mat(s)

matrix([[ 12,  32,  23, 545,  32]])

In [32]:
np.array(s)

array([ 12,  32,  23, 545,  32])

In [34]:
np.asanyarray(np.mat(s))

matrix([[ 12,  32,  23, 545,  32]])

In [36]:
np.fromfunction(lambda i,j:i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i,j:i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
np.mat(np.fromfunction(lambda i,j:i*j ,(3,3)))

matrix([[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]])

In [43]:
np.fromfunction(lambda i,j,z:i*j*z ,(3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [44]:
np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])