In [1]:
import numpy as np

In [3]:
l=[12,23,32,54]

In [4]:
np.array(l)

array([12, 23, 32, 54])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#broadcasting
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [12]:
np.empty((2,3,4))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         4.67293691e-307],
        [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
         6.23053954e-307],
        [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
         9.34603000e-307]],

       [[1.78018403e-306, 8.90106955e-307, 1.60218491e-306,
         1.78018403e-306],
        [1.69119330e-306, 6.23054633e-307, 1.24610927e-306,
         1.05698817e-307],
        [1.11261638e-306, 1.33511562e-306, 2.22522596e-306,
         2.22507386e-306]]])

In [13]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [19]:
np.linspace(0,10,10).reshape(5,2)

array([[ 0.        ,  1.11111111],
       [ 2.22222222,  3.33333333],
       [ 4.44444444,  5.55555556],
       [ 6.66666667,  7.77777778],
       [ 8.88888889, 10.        ]])

In [23]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [28]:
a=np.arange(4,20).reshape(4,4)

In [29]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
a.max()

19

In [3]:
a=np.array([12,23,23,54,23])

In [4]:
b=np.array([12,32,23,54,23])

In [5]:
a+b

array([ 24,  55,  46, 108,  46])

In [6]:
b=b.reshape(1,-1)

In [7]:

b

array([[12, 32, 23, 54, 23]])

In [9]:
b.T+a

array([[ 24,  35,  35,  66,  35],
       [ 44,  55,  55,  86,  55],
       [ 35,  46,  46,  77,  46],
       [ 66,  77,  77, 108,  77],
       [ 35,  46,  46,  77,  46]])

In [10]:
id(a)

1727822980432

In [11]:
id(b)

1727822985808